NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 9999999;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 9999999;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 9999999;
NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.00015;
NDefines.NMilitary.BATALION_CHANGED_EXPERIENCE_DROP = 0.2;
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 1.5;
NDefines.NNavy.LEADER_EXPERIENCE_SCALE = 1.5;