NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 9999999;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 9999999;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 9999999;
NDefines.NMilitary.MAX_FIELD_EXPERIENCE_ON_DIVISION = 15000;
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.1;
NDefines.NCharacter.SPECIALIST_ADVISOR_MIN_RANK = 4;
NDefines.NCharacter.EXPERT_ADVISOR_MIN_RANK = 6;
NDefines.NCharacter.GENIUS_ADVISOR_MIN_RANK = 10;